### PR TITLE
Updated ReadMe

### PR DESCRIPTION
**Pull request by IntelligentIndia7**
ReadMe with more elaborate instructions to install and also updated possible issues and solutions.

### CODE REVIEW

**Comment by IntelligentIndia7** [comment]
@xbpeng Hey, I have just updated the instructions to be able to setup the environment, run and train the Deep Mimic environment. Thought it'll be useful for anyone to setup the environment. Thank you.

**Comment by SleepingFox88** [comment]
When viewing files changed, I see you put command line instructions on their own individual lines

[](https://i.imgur.com/HPFDHg7.jpg)

However when viewing the ReadMe.md as it normally displays itself, the instructions are all jumbled together on a single line, without much indication of where each instruction begins and ends.

[](https://i.imgur.com/YUsKknW.jpg)

**Comment by SleepingFox88** [comment]
I recommend updating this pull request to include the changes in the [repo found here](https://github.com/SleepingFox88/DeepMimic/tree/Updated-ReadMe). I have attempted to pull request these changes into [IntelligentIndia7:master](https://github.com/IntelligentIndia7/DeepMimic) but could not find it as an option to pull request into.

**Comment by xbpeng** [comment]
Awesome, thanks a lot for adding more detailed instructions! I'll get this merged. Sorry about the delay on this.

**Comment by xbpeng** [comment]
@SleepingFox88 Thanks for fixes. I've updated the readme in master with your changes.

**Comment by SleepingFox88** [comment]
Oof, I got no commit credit for aaaf3f0bc6f6c948eb2fb392792077dfa6f31459

Still I am happy to have helped :)

**Pull request merged**
